### PR TITLE
formula can be an answer response

### LINKED ISSUE #1906: Answer checking with missing formula state variable crashes browser
See linked file. If the answer block contains an award component which compares a math to a function, and the user forgets to include the formula state variable on the function, the browser crashes.
https://www.doenet.org/public?tool=editor&doenetId=_tFsovzZw8tnMTGGAo9bp6&pageId=_kGN1TNWaCEusW9Ew8bUSo

### PR DESCRIPTION
**Pull request by dqnykamp**
Fixes #1906

### CODE REVIEW

File: src/Core/components/Answer.js [hunk 1]
```diff
@@ -988,9 +989,15 @@ export default class Answer extends InlineComponent {
             currentResponses.push(...component.stateValues.values)
             componentType.push(...Array(component.stateValues.values.length)
               .fill(ct));
-          } else {
+          } else if (component.stateValues.value !== undefined) {
             currentResponses.push(component.stateValues.value)
             componentType.push(ct)
+          } else if (component.stateValues.formula instanceof me.class) {
```
Comment (jaltekruse) [inline src/Core/components/Answer.js:995]: Not worth blocking this bugfix PR, but notating for the future I had a discussion with Duane about if we might want to formalize a concept of declaring a "primary" state variable for a component. For example here I would prefer we not have and instanceof check and instead be able to refer to the "value" state variable for all cases. Although admittedly creating an "alias" for the formula state variable that would be called value would be confusing because it likely would make people think about the value of the function evaluated for a given input.

**Review by jaltekruse — APPROVED** [review]
+1
