### PR TITLE
Fix rename content

### LINKED ISSUE #2575: Renaming bug
When trying to rename a document/folder in alpha, if one clicks outside the name field, the change goes through without issue. However, if one presses Enter, the error in the video shows up. Tested in Chrome. 

https://github.com/user-attachments/assets/8139363d-e4cd-448f-bc66-515e9ca5e5ce

### PR DESCRIPTION
**Pull request by cqnykamp**
Renaming content and pressing enter no longer displays an error page. Resolves #2575

Also clean up React Router paths.

### CODE REVIEW

File: client/src/drawerTabs/GeneralContentControls.tsx [hunk 1]
```diff
@@ -25,6 +25,7 @@ import { activityFeatureIcons } from "../utils/activity";
 import { MdError } from "react-icons/md";
 
 export async function generalContentActions({ formObj }: { [k: string]: any }) {
+  console.log(`action with name ${formObj._action}`, formObj);
```
Comment (dqnykamp) [inline client/src/drawerTabs/GeneralContentControls.tsx:28]: remove console.log

File: client/src/index.tsx [hunk 2]
```diff
@@ -329,7 +271,7 @@ const router = createBrowserRouter([
       },
       {
         path: "assignedData",
-        loader: assignedDataloader,
+        loader: studentAssignmentScoresLoader,
```
Comment (dqnykamp) [inline client/src/index.tsx:274]: Just making sure that this switch of loaders was intentional and desired.

**Review by dqnykamp — CHANGES_REQUESTED** [review]
Looks good other than one minor comment.
